[package]
name = "reddit-cargo-build"
version = "0.1.0"
authors = ["Your Email & Name"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.15.3"
